config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :tags
  get "search" => "tags#search"
  # For details on the DS,L available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  #タグ機能
  acts_as_taggable_on :tags

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  #コメント機能
  has_many :book_comments, dependent: :destroy

  #閲覧数
  has_many :view_counts, dependent: :destroy

  #タグ機能
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :tags, through: :book_tag_relations
  # accepts_nested_attributes_for :book_tag_relations, allow_destroy: true
  # accepts_nested_attributes_for :tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 #スコープ機能を駆使して「今日・機能・今週・先週」のデータを取り出すための記述をモデルに行い、コントローラでの記述をすっきりさせる。（2日前〜6日前までも含む）
 scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
 scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
 scope :created_2days, -> { where(created_at: 2.day.ago.all_day)}
 scope :created_3days, -> { where(created_at: 3.day.ago.all_day)}
 scope :created_4days, -> { where(created_at: 4.day.ago.all_day)}
 scope :created_5days, -> { where(created_at: 5.day.ago.all_day)}
 scope :created_6days, -> { where(created_at: 6.day.ago.all_day)}
 scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
 scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 scope :latest, -> { order(created_at: :desc) }
 scope :star_count, -> { order(star: :desc) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/book_tag_relation.rb
class BookTagRelation < ApplicationRecord
  # belongs_to :book
  # belongs_to :tag
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

has_many :group_users
has_many :users, through: :group_users

validates :name, presence: true
validates :introduction, presence: true
has_one_attached :image

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join("app/assets/images/no_image.jpg")
    image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
  end
  image.variant(resize_to_limit: [width, height]).processed
end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  #DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :books, through: :book_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :book_comments, dependent: :destroy

# フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :follower
has_many :followers, through: :reverse_of_relationships, source: :following

#DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy

#閲覧数
has_many :view_counts, dependent: :destroy

#グループ作成
has_many :group_users
has_many :groups, through: :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: "guestuser" ,email: "guest@guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

 def index
   @groups = Group.all
   @book = Book.new
   @user = current_user
 end

 def new
   @group = Group.new
 end

 def create
   @group = Group.new(group_params)
   @group.owner_id = current_user.id
   @group.users << current_user
   if @group.save
     redirect_to groups_path
   else
     render 'new'
   end
 end

 def join
   @group = Group.find(params[:group_id])
   @group.users << current_user
   redirect_to groups_path
 end

 def show
   @group = Group.find(params[:id])
   @book = Book.new
   @user = current_user
 end

 def edit
 end

 def update
   if @group.update(group_params)
     redirect_to groups_path
   else
     render 'edit'
   end
 end

 def destroy
   @group = Group.find(params[:id])
   @group.users.destroy(current_user)
   redirect_to groups_path
 end
 
 def new_mail
   @group = Group.find(params[:group_id])
 end
 
 def send_mail
   @group = Group.find(params[:group_id])
   group_users = @group.users
   @mail_title = params[:mail_title]
   @mail_content = params[:mail_content]
   ContactMailer.send_mail(@mail_title, @mail_content,group_users).deliver
 end

 private

 def group_params
   params.require(:group).permit(:name, :introduction, :image)
 end

 def ensure_correct_user
   @group = Group.find(params[:id])
   unless @group.owner_id == current_user.id
     redirect_to groups_path
   end
 end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>

 <div class="form-group">
   <%= f.label :グループ名 %>
   <%= f.text_field :name, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :紹介文 %>
   <%= f.text_area :introduction, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :グループ画像 %>
   <%= f.file_field :image, class: 'form-control_file' %>
 </div>

 <div class="form-group">
   <%= f.submit 'Create Group', class: 'btn btn-info' %>
 </div>

<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8, mx-auto">
       <h1>Editing Group</h1>
         <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
 <div class="container">
  <div class="row">
   <%= render 'books/sideber', book: @book, user: @user %>

   <div class="col-md-8 offset-md-1">
    <h2>Groups</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
       <% @groups.each do |group| %>
        <tr>
          <td><%= image_tag group.get_image(100, 100) %></td>
          <td>
           <%= link_to group_path(group) do %>
            <%= group.name %>
           <% end %>
            </td>
          <td><%= group.introduction %></td>
          <td><%= group.users.count %></td>
          <td>
            <% if group.owner_id == current_user.id %>
             <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-success btn-sm' %>
            <% end %>
          </td>
        </tr>
       <% end %>
      </tbody>
    </table>

   </div>
  </div>
 </div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8, mx-auto">
       <h1>Create Group</h1>
         <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1>Event Mail</h1>
      <%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
       <div class="form-group">
         <%= f.label :Title %>
         <%= f.text_field :mail_title, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.label :Content %>
         <%= f.text_field :mail_content, class: 'form-control' %>
       </div>
       <div>
         <%= f.submit '送信' %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>送信が完了しました</h1>
      <div class="send_mail_messages">
        <div>内容は以下のとおりです。</div>
        <div class="mail_group">
          [タイトル]
          <p class="font-weight-bold"><%= @mail_title %></p>
        </div>
        <div class="mail_group">
          [本文]
          <p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
   <%= render 'books/sideber', book: @book, user: @user %>

   <div class="col-md-8 offset-md-1">
    <h2>Group Detail</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th>メンバー</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag @group.get_image(100, 100) %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group.users.each do |member| %>
             <%= member.name %>
            <% end %>
          </td>
          <td>
            <% if @group.owner_id == current_user.id %>
             <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-success btn-sm' %>
            <% elsif @group.users.include?(current_user) %>
             <%= link_to 'Leave this group', group_path(@group), method: :delete, class: 'btn btn-danger btn-sm' %>
            <% else %>
             <%= link_to 'Join this group', group_join_path(@group),  class: 'btn btn-success btn-sm' %>
            <% end %>
          </td>
          <td>
            <% if @group.owner_id  == current_user.id %>
             <%= link_to 'Notice an Event', group_new_mail_path(@group), method: :get, class: 'btn btn-info btn-sm' %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

   </div>
  </div>
 </div>