config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :tags
  get "search" => "tags#search"
  # For details on the DS,L available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  #タグ機能
  acts_as_taggable_on :tags

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  #コメント機能
  has_many :book_comments, dependent: :destroy

  #閲覧数
  has_many :view_counts, dependent: :destroy

  #タグ機能
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :tags, through: :book_tag_relations
  # accepts_nested_attributes_for :book_tag_relations, allow_destroy: true
  # accepts_nested_attributes_for :tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 #スコープ機能を駆使して「今日・機能・今週・先週」のデータを取り出すための記述をモデルに行い、コントローラでの記述をすっきりさせる。（2日前〜6日前までも含む）
 scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
 scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
 scope :created_2days, -> { where(created_at: 2.day.ago.all_day)}
 scope :created_3days, -> { where(created_at: 3.day.ago.all_day)}
 scope :created_4days, -> { where(created_at: 4.day.ago.all_day)}
 scope :created_5days, -> { where(created_at: 5.day.ago.all_day)}
 scope :created_6days, -> { where(created_at: 6.day.ago.all_day)}
 scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
 scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 scope :latest, -> { order(created_at: :desc) }
 scope :star_count, -> { order(star: :desc) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/book_tag_relation.rb
class BookTagRelation < ApplicationRecord
  # belongs_to :book
  # belongs_to :tag
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

has_many :group_users
has_many :users, through: :group_users

validates :name, presence: true
validates :introduction, presence: true
has_one_attached :image

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join("app/assets/images/no_image.jpg")
    image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
  end
  image.variant(resize_to_limit: [width, height]).processed
end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  #DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :books, through: :book_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :book_comments, dependent: :destroy

# フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :follower
has_many :followers, through: :reverse_of_relationships, source: :following

#DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy

#閲覧数
has_many :view_counts, dependent: :destroy

#グループ作成
has_many :group_users
has_many :groups, through: :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: "guestuser" ,email: "guest@guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
    @users_unwhere = User.where.not(id: current_user.id)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def show
   @user = User.find(params[:id])
    #DM機能
   @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    #DM機能
    @books = @user.books
    @book_new = Book.new
  end

  def daily_posts
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users = User.all
      render:edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(user_path(current_user.id)) unless @user == current_user
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.name == "guestuser"
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: 'row justify-content-center', local: false do |f|  %>
   <div class="col-auto">
    <%= f.date_field :created_at, class: 'form-control' %>
   </div>
   <div class="col-auto">
    <%= f.submit '検索', class: 'btn btn-primary' %>
   </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class="container mt-3">
 <div class="row">
  <div class="col-lg-5 mx-auto px-0">
    <h2 class="mb-3">User info</h2>
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
     <% end %>
     <%= form_with model: @user do |f| %>

      <div class="form-group">
       <div class="name-head"><label for="inputName">Name</label></div>
       <%= f.text_field :name, id:"inputName", placeholder:"名前", class: 'border border-1 rounded col-12  form-control' %>
      </div>

      <div class="form-group">
       <div class="image-head"><label for="inputimage">Image</label></div>
       <%= f.file_field :profile_image,  placeholder:"プロフィール画像"  %>
      </div>


      <div class="form-group">
       <div class="opinion-head"><label for="inputIntroduction">Introduction</label></div>
       <%= f.text_area :introduction,  class: 'border border-1 rounded col-12 form-control' %>
      </div>

     <%= f.submit 'Update User', class: 'btn btn-secondary mb-3'%>
     <% end %>

  </div>
 </div>
</div>

app/views/users/index.html.erb
<!--Userinfoの作成-->
<div class="container mt-3 px-0">
  <div class="row">
     <!--部分テンプレートの作成-->
    <%= render '/books/sideber', book: @book, user: @user %>

 <!--ユーザー一覧の作成-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to 'グループを作成する', new_group_path %>｜<%= link_to 'グループ一覧', groups_path %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th>image</th>
           <th>name</th>
           <th></th>
           <th></th>
           <th></th>
           <th></th>
          </tr>
        </thead>

        <tbody>
         <% @users.each do |user| %>
          <tr>
           <td><%= image_tag user.get_profile_image(100, 100) %></td>
           <td><%= user.name %></td>
           <td>フォロー数：<%= user.followings.count %></td>
           <td>フォロワー数：<%= user.followers.count %></td>
           <td>
            <% if user.is_followed_by?(current_user) %>
             <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
             <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
            <% end %>
           </td>
           <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--Userinfoの作成-->
<div class="container mt-3">
  <div class="row">
     <!--部分テンプレートの作成-->
<%= render '/books/sideber', book: @book_new, user: @user, roomId: @roomId, room: @room, entry: @entry, isRoom: @isRoom %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
         <% @books.each do |book| %>
          <tr>
           <td>
           <%= link_to user_path(@user.id) do%>
           <%= image_tag book.user.get_profile_image(100, 100) %>
           <% end %>
           </td>
           <td><%= link_to book.title, book_path(book.id) %></td>
           <td><%= book.body %></td>
           <td>
             <div class="star" id="review-star<%= book.id %>"></div>
           </td>
                <script>
                    elem = document.querySelector('#review-star<%= book.id %>');
                    opt = {
                     size :38,
                     starOff: '<%= asset_path('star-off.png') %>',
                     starOn: '<%= asset_path('star-on.png') %>',
                     half: false,
                     readOnly: true,
                     score: '<%= book.star %>'
                    };
                   raty(elem,opt);
                </script>

           <td></td>
          </tr>
         <% end %>
        </tbody>
      </table>
      <%= render 'daily_posts_form', user: @user %>
    </div>
  </div>
</div>