config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :tags
  get "search" => "tags#search"
  # For details on the DS,L available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  #タグ機能
  acts_as_taggable_on :tags

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  #コメント機能
  has_many :book_comments, dependent: :destroy

  #閲覧数
  has_many :view_counts, dependent: :destroy

  #タグ機能
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :tags, through: :book_tag_relations
  # accepts_nested_attributes_for :book_tag_relations, allow_destroy: true
  # accepts_nested_attributes_for :tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 #スコープ機能を駆使して「今日・機能・今週・先週」のデータを取り出すための記述をモデルに行い、コントローラでの記述をすっきりさせる。（2日前〜6日前までも含む）
 scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
 scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
 scope :created_2days, -> { where(created_at: 2.day.ago.all_day)}
 scope :created_3days, -> { where(created_at: 3.day.ago.all_day)}
 scope :created_4days, -> { where(created_at: 4.day.ago.all_day)}
 scope :created_5days, -> { where(created_at: 5.day.ago.all_day)}
 scope :created_6days, -> { where(created_at: 6.day.ago.all_day)}
 scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
 scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 scope :latest, -> { order(created_at: :desc) }
 scope :star_count, -> { order(star: :desc) }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    # to = Time.current.at_end_of_day
    # from = (to - 6.day).at_beginning_of_day
    # @books = Book.includes(:favorited_users).
    # sort_by {|x|
    #   x.favorited_users.includes(:favorites).where(created_at: from...to).size
    # }.reverse
    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end

    @book = Book.new
    # if params[:tag_name]
    #   @books = Book.tagged_with("#{params[:tag_name]}")
    # end

    # @books = Book.all　※いいねが多い順に並べるためコメントアウト
    @user = current_user
    #閲覧数
    unless ViewCount.find_by(user_id: current_user.id, book_id: @books)
      current_user.view_counts.create(book_id: @books)
    end

    #投稿数比較機能
    @book_creates = Book.all
    @today_books = @book_creates.created_today
    @yesterday_books = @book_creates.created_yesterday
    @days2_ago_books = @book_creates.created_2days
    @days3_ago_books = @book_creates.created_3days
    @days4_ago_books = @book_creates.created_4days
    @days5_ago_books = @book_creates.created_5days
    @days6_ago_books = @book_creates.created_6days
    @this_week_books = @book_creates.created_this_week
    @last_week_books = @book_creates.created_last_week

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render:index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    #閲覧数
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @user = @book.user

    #コメント機能
    @book_comment = BookComment.new

  end

  def edit
    # @book = Book.find(params[:id])
  end

  def update
    # @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render:edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    # @book.user_id = current_user.id
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :star, :tag_list)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
     redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<% books.each do |book| %>
  <tr id="book_<%= book.id %>">
     <td>
       <%= link_to user_path(book.user) do%>
        <%= image_tag book.user.get_profile_image(100, 100) %>
       <% end %>
     </td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
     <td><%= render 'tag', tag_list: book.tag_list %></td>
     <td class="favorite_btn">
       <%= render 'favorites/btn', book: book %>
     </td>
     <td class="comment_counts">コメント数<%= book.book_comments.count %></td>
     <td>
       <div class="review-star"></div>
     </td>
          <script>
              elem = document.querySelector('#book_<%= book.id %> .review-star');
              opt = {
               size :38,
               starOff: '<%= asset_path('star-off.png') %>',
               starOn: '<%= asset_path('star-on.png') %>',
               half: false,
               readOnly: true,
               score: '<%= book.star %>'
              };
             raty(elem,opt);
          </script>

     <td class="view_counts">閲覧数<%= book.view_counts.count %></td>
  </tr>
<% end %>

app/views/books/_sideber.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <%= image_tag user.get_profile_image(100, 100) %>
   <table class="mb-4 col-12">
    <tbody>
     <tr class="border-top">
      <th class="p-3">name</th>
      <th><%= user.name %></th>
     </tr>

     <tr class="border-top">
      <th class="p-3">introduction</th>
      <th><%= user.introduction %></th>
     </tr>

     <tr class="border-top">
      <th class="p-3">follows</th>
      <th><%= user.followings.count %></th>
     </tr>

      <tr class="border-top">
       <th class="p-3">followers</th>
       <th><%= user.followers.count %></th>
     </tr>

    </tbody>
   </table>
   <% if user.name != "guestuser" %>
    <div class="row">
     <%= link_to(edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block') do %>
       <i class="fas fa-user-cog"></i>
     <% end %>
    <% end %>
    </div>

    <div class="row mt-3">
     <% if user.is_followed_by?(current_user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: 'btn btn-danger' %>

      <% unless user.id == current_user.id %>
      <% if (current_user.is_followed_by? user) && (user.is_followed_by? current_user) %>
      <% if isRoom == true %>
       <%= link_to 'チャットへ', room_path(roomId), class: 'btn btn-primary btn-lg' %>
       <!--<p class="user-show-room"><a href="/rooms/<%#= roomId %>" class="btn btn-primary btn-lg">チャットへ</a></p>-->
      <% else %>
       <%= form_for room do |f| %>
        <%= fields_for entry do |e| %>
         <%= e.hidden_field :user_id, value: user.id %>
        <% end %>
        <%= f.submit "チャットを始める", class: "btn btn-primary btn-lg user-show-chat" %>
       <% end %>
      <% end %>
      <% end %>
     <% end %>

     <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'btn btn-info' %>
     <% end %>
    </div>


    <!--新規投稿フォームの作成-->
    <%= form_with model: book, url: books_path, method: :post do |f| %>
    <!-- @book → book -->
     <h2 class="mt-3">New book</h2>
      <div class="book_group mb-3">
       <div class="book_title mb-2">Title</div>
         <%= f.text_field :title, class: 'border border-1 rounded col-12 form-control' %>
      </div>
      <div class="book_group mb-3">
       <div class="book_opinion mb-2">Opinion</div>
        <%= f.text_area :body, class: 'border border-1 rounded col-12 form-control' %>
       </div>

       <!--タグ機能-->
       <div class="book_group mb-3">
        <div class="book_tag mb-2">Tag</div>
         <%= f.text_field :tag_list, value: book.tag_list.join(',')  ,class: 'border border-1 rounded col-12 form-control' %>
       </div>

             <!--星レビューフォームの作成-->
       <div class ="star-review mb-2" id="post_raty">
        <%= f.label :star %>
       </div>

       <script>
         // scriptファイルをどのidの部分に配置するかを指定
         let elem = document.querySelector('#post_raty');
         let opt = {
           size :38,
           starOff: '<%= asset_path('star-off.png') %>',
           starOn: '<%= asset_path('star-on.png') %>',
           scoreName: 'book[star]',
           half: false
          };
         raty(elem,opt);
       </script>

       <%= f.submit 'Create Book', class: 'btn btn-success' %>

     <% end %>



</div>

app/views/books/_tag.html.erb
<% tag_list.each do |tag| %>
  <%= link_to tag, tags_path(tag_name: tag), class: 'text_white' %>
<% end %>

app/views/books/edit.html.erb
<div class="container mt-3">
 <div class="row">
  <div class="col-lg-5 mx-auto px-0">
    <h1 class="mb-3">Editing Book</h1>
    　 <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
     <% end %>
     <%= form_with model: @book do |f| %>

      <div class="form-group">
       <div class="title-head"><label for="title">Title</label></div>
       <%= f.text_field :title, class: 'border border-1 rounded col-12 input-lg' %>
      </div>

      <div class="form-group">
       <div class="opinion-head"><label for="opinion">Opinion</label></div>
       <%= f.text_area :body, class: 'border border-1 rounded col-12 input-lg' %>
      </div>

     <%= f.submit 'Update Book', class: 'btn btn-success mb-3'%>
     <% end %>

    <%= link_to 'Show', book_path(@book.id) %> |
    <%= link_to 'Back', books_path %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<!--Userinfoの作成-->
<div class="container mt-3 px-0">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
     <% end %>
  <div class="row">

     <!--部分テンプレートの作成-->
    <%= render 'sideber', book: @book, user: @user %>
    <!--投稿一覧の作成-->
    <div class="col-md-8 offset-md-1">

     <%= render 'tags/search', book: @book %>

      <h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>｜<%= link_to '評価の高い順', books_path(star_count: "true") %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th>Tag</th>
           <th></th>
           <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
         <%= render 'index', books: @books, book_detail: @book_detail %>
        </tbody>
      </table>

      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_books.count %></td>
            <td><%= @yesterday_books.count %></td>
            <% if @yesterday_books.count == 0 %>
             <td>前日の投稿なし</td>
            <% else %>
             <td><% @the_day_before = @today_books.count / @yesterday_books.count.to_f %>
                 <%= (@the_day_before * 100).round %>%</td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_books.count %></td>
            <td><%= @last_week_books.count %></td>
            <% if @last_week_books.count == 0 %>
             <td>前週の投稿なし</td>
            <% else %>
             <td><% @the_week_before = @this_week_books.count / @last_week_books.count.to_f %>
                 <%= (@the_week_before * 100).round %>%</td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <h2>7日間分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @days6_ago_books.count %></td>
            <td><%= @days5_ago_books.count %></td>
            <td><%= @days4_ago_books.count %></td>
            <td><%= @days3_ago_books.count %></td>
            <td><%= @days2_ago_books.count %></td>
            <td><%= @yesterday_books.count %></td>
            <td><%= @today_books.count %></td>
          </tr>
        </tbody>
      </table>

      <div>
        <canvas id="myChart"></canvas>
      </div>

      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

      <script>
        const ctx = document.getElementById('myChart');

        new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
              label: '投稿した本の数',
              data: [<%= @days6_ago_books.count %>, <%= @days5_ago_books.count %>, <%= @days4_ago_books.count %>, <%= @days3_ago_books.count %>, <%= @days2_ago_books.count %>, <%= @yesterday_books.count %>, <%= @today_books.count %>],
              borderWidth: 2
            }]
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
       </script>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
 <div class="row">
<!--部分テンプレートの作成-->
<%= render 'sideber', book: @book_new, user: @user %>

<!--詳細画面の作成-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table font-small">
        <tbody>

          <tr id="book_<%= @book.id %>">
            <td>
              <%= link_to user_path(@user.id) do %>
               <%= image_tag @book.user.get_profile_image(100, 100) %><br><%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title,  book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <td><%= render 'tag', tag_list: @book.tag_list %></td>
            <td class="comment_counts">コメント数<%= @book.book_comments.count %></td>
            <td>
              <div class="star" id="review-star<%= @book.id %>"></div>
            </td>
                <script>
                    elem = document.querySelector('#review-star<%= @book.id %>');
                    opt = {
                     size :38,
                     starOff: '<%= asset_path('star-off.png') %>',
                     starOn: '<%= asset_path('star-on.png') %>',
                     half: false,
                     readOnly: true,
                     score: '<%= @book.star %>'
                    };
                   raty(elem,opt);
                </script>


            <td>閲覧数<%= @book.view_counts.count %></td>
            <td>
              <% if @book.user == current_user %>
               <%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-success btn-sm'%>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
               <%= link_to 'Destroy', book_path(@book.id), method: :delete,  "data-confirm" => "本当に消しますか?", class: 'btn btn-danger btn-sm' %>
              <% end %>
            </td>
          </tr>

          <tr class="row comment-index">
            <%= render 'book_comments/index', book: @book %>
          </tr>

          <tr class="row comment-form">
            <td class="col-5">
              <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
            </td>
          </tr>

        </tbody>
      </table>



    </div>
  </div>
</div>