config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :tags
  get "search" => "tags#search"
  # For details on the DS,L available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  #タグ機能
  acts_as_taggable_on :tags

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  #コメント機能
  has_many :book_comments, dependent: :destroy

  #閲覧数
  has_many :view_counts, dependent: :destroy

  #タグ機能
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :tags, through: :book_tag_relations
  # accepts_nested_attributes_for :book_tag_relations, allow_destroy: true
  # accepts_nested_attributes_for :tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 #スコープ機能を駆使して「今日・機能・今週・先週」のデータを取り出すための記述をモデルに行い、コントローラでの記述をすっきりさせる。（2日前〜6日前までも含む）
 scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
 scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
 scope :created_2days, -> { where(created_at: 2.day.ago.all_day)}
 scope :created_3days, -> { where(created_at: 3.day.ago.all_day)}
 scope :created_4days, -> { where(created_at: 4.day.ago.all_day)}
 scope :created_5days, -> { where(created_at: 5.day.ago.all_day)}
 scope :created_6days, -> { where(created_at: 6.day.ago.all_day)}
 scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
 scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 scope :latest, -> { order(created_at: :desc) }
 scope :star_count, -> { order(star: :desc) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/book_tag_relation.rb
class BookTagRelation < ApplicationRecord
  # belongs_to :book
  # belongs_to :tag
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord

has_many :group_users
has_many :users, through: :group_users

validates :name, presence: true
validates :introduction, presence: true
has_one_attached :image

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join("app/assets/images/no_image.jpg")
    image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
  end
  image.variant(resize_to_limit: [width, height]).processed
end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  #DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_many :book_tag_relations, dependent: :destroy
  # has_many :books, through: :book_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :book_comments, dependent: :destroy

# フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :follower
has_many :followers, through: :reverse_of_relationships, source: :following

#DM機能
has_many :entries, dependent: :destroy
has_many :messages, dependent: :destroy

#閲覧数
has_many :view_counts, dependent: :destroy

#グループ作成
has_many :group_users
has_many :groups, through: :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: "guestuser" ,email: "guest@guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    if params[:tag_name]
      @books = Book.tagged_with("#{params[:tag_name]}")
    else
      @books = Book.all
    end
    @keyword = params[:tag_name]
  end

  def search
    if params[:key]
      @books = Book.tagged_with("#{params[:key]}")
    else
      @books = Book.all
    end
    @keyword = params[:key]
    render 'index'
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tags/_search.html.erb
<%= form_with url: search_path, local: true, method: :get do |f| %>
 <%= f.text_field :key, value: book.tag_list.join(','), class: 'text_white' %>
 <%= f.submit 'タグ検索' %>
<% end %>

app/views/tags/index.html.erb
<h3>books_search_for"<%= @keyword %>"</h3>

 <table class="table table-hover table-inverse">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th>Tag</th>
           <th></th>
           <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr id="book_<%= book.id %>">
             <td>
               <%= link_to user_path(book.user) do%>
                <%= image_tag book.user.get_profile_image(100, 100) %>
               <% end %>
             </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
             <td><%= render 'books/tag', tag_list: book.tag_list %></td>
             <td class="favorite_btn">
               <%= render 'favorites/btn', book: book %>
             </td>
             <td class="comment_counts">コメント数<%= book.book_comments.count %></td>
             <td>
               <div class="review-star"></div>
             </td>
                  <script>
                      elem = document.querySelector('#book_<%= book.id %> .review-star');
                      opt = {
                       size :38,
                       starOff: '<%= asset_path('star-off.png') %>',
                       starOn: '<%= asset_path('star-on.png') %>',
                       half: false,
                       readOnly: true,
                       score: '<%= book.star %>'
                      };
                     raty(elem,opt);
                  </script>

             <td class="view_counts">閲覧数<%= book.view_counts.count %></td>
          </tr>
         <% end %>
        </tbody>
  </table>